# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: poc222.blackduck.synopsys.com

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'

- task: BlackDuckSecurityScan@2
  displayName: 'Black Duck SCA Scan'
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
  inputs:
    blackducksca_url: $(BLACKDUCK_URL)
    blackducksca_token: $(BLACKDUCK_API_TOKEN)
    blackducksca_scan_failure_severities: 'BLOCKER'
    blackducksca_fixpr_enabled: true
    blackducksca_prcomment_enabled: true
    blackducksca_reports_sarif_create: true
    #azure_token: $(System.AccessToken)
    mark_build_status: 'SucceededWithIssues'
    # include_diagnostics: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
